# Generated by Django 5.1.1 on 2024-09-09 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned')], default='available', max_length=10)),
                ('borrowed_by', models.ManyToManyField(blank=True, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
