# Generated by Django 5.1.1 on 2024-09-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], default='available', max_length=10),
        ),
    ]
